apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-health-check
  namespace: quakewatch
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: health-check
              image: curlimages/curl:latest
              command:
                - sh
                - -c
                - |
                  echo "Checking QuakeWatch service..."
                  curl -f http://quakewatch-service.quakewatch.svc.cluster.local/ || exit 1
                  echo "QuakeWatch is up"
